# Generated by Django 3.2.5 on 2023-01-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommender', '0002_course_drive_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
    ]
