# Generated by Django 3.2.5 on 2023-01-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommender', '0003_auto_20230105_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
