# Generated by Django 3.2.5 on 2023-01-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommender', '0004_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
