# Generated by Django 3.2.5 on 2023-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recommender', '0005_auto_20230105_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='drive_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city_name',
            field=models.TextField(max_length=100),
        ),
    ]
